name: flutter_sharez
description: ""
version: 1.0.9+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ai_barcode_scanner: ^3.4.1
  alfred: ^1.1.1
  auto_route: ^7.8.4
  dart_jwt_token: ^0.0.3
  device_preview: ^1.1.0
  device_preview_screenshot: ^1.0.0
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  duration: ^3.0.13
  file_picker: ^6.1.1
  file_sizes: ^1.0.6
  flash: ^3.1.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_form_builder: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18+2
  flutter_native_splash: ^2.3.8
  flutter_riverpod: ^2.4.9
  flutter_speed_dial: ^7.0.0
  hive_flutter: ^1.1.0
  hyper_thread_downloader: ^1.0.5+3
  internet_connection_checker_plus: ^2.1.0
  intl: ^0.18.1
  lottie: ^2.7.0
  multiple_result: ^5.1.0
  network_discovery: ^1.0.0
  open_app_file: ^4.0.2
  package_info_plus: ^4.2.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  platform_info: ^4.0.2
  qr_flutter: ^4.1.0
  responsive_framework: ^1.1.1
  talker_dio_logger: ^2.4.0
  talker_flutter: ^3.6.0
  url_launcher: ^6.2.2
  velocity_x: ^4.1.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.6
  mocktail: ^1.0.2
  riverpod_lint: ^2.3.7
  riverpod_test: ^0.1.4
  spot: ^0.7.0
  very_good_analysis: ^5.1.0






flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo/
    - assets/anim/

