name: flutter_sharez
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.7.0
  dio: ^5.2.1+1
  dio_smart_retry: ^5.0.0
  duration: ^3.0.12
  flash: ^3.0.5+1
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  path_provider: ^2.0.15
  platform_info: ^4.0.2
  responsive_framework: ^1.1.0
  talker_dio_logger: ^2.1.2
  talker_flutter: ^3.1.5
  velocity_x: ^4.1.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  riverpod_lint: ^1.3.2
  riverpod_test: ^0.1.3
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo/
    - assets/anim/

